### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by Akashiutchiha** [Skilltechs/funspace#11]
No logo for this organisation till now. We need to work on the logo too for us to publish results we must have an emblem that defines us.

**Comment by KajiAime** [comment]
I have two tasks on my shoulders already. Therefore, I will make sure I resolve them.

**Comment by KajiAime** [comment]
Having a gradient as we said.

**Comment by Akashiutchiha** [comment]
Good luck.

**Comment by mulfranck** [comment]
Please the logo is for funspace not skilltechs.

1. You need to have a sketch of what logo you want to design.
2. The colors you use is the color that defines funspace or the colors funspace would make use of.

So for now, have the sketch and send it for approval to the group.
Thank you.

**Comment by KajiAime** [comment]
Ok. I get that. I will choose them wisely.

**Comment by Akashiutchiha** [comment]
Ok
