### ISSUE TITLE
Still trying to understand how we can collaborate

### ISSUE THREAD

**Issue by mulfranck** [Skilltechs/funspace#5]
### Hello to every member of this project.
You can still remember we have difficulties on how everyone can be updated with the current and latest version of this project.
While we trying this solution, please keep working on your `forked` repo.

### This issue is meant to give you some tries.

- Firstly, every member of this project must **watch** this repository [just look beside the Fork tag at the right top].
- Next, you reply to this message.
  - [x] @Akashiutchiha 
  - [x] @mulfranck
  - [x] @KajiAime  
  - [x] @Ronaldyika
  - [x]  @Livingstonkongnyuy 

Then we can talk of the thought of solution.

_Thank you._

**Comment by Akashiutchiha** [comment]
See while we are trying to solve this issue. We will work locally as it was
done before git came into play. We will be using USB Keys to exchange
codes. And the administrators will be commiting them on git.
Am proposing.

**Comment by mulfranck** [comment]
**I think this would be a pain.**
if the I change some files for my own copy and you change some files in your own copy.

*For example*; As I am working on `Js` they would be time that I would change an element or two in the `HTML` file, and you are working on the `PHP` maybe you would change one or more this in your copy, and the group for `HTML`, what if they made some change while we are making some change on our side.

**How would we merge this copies into one?**

**Comment by Akashiutchiha** [comment]
Ok. If we resolve our problem with git. Fine if not we will be forced to do
so while waiting

**Comment by kendah-bryan** [comment]
Please what is a Todo list in the first place

**Comment by KajiAime** [comment]
A list which shows in an organised pattern what we have to do. It is a checklist, and so at some points it will also contain what we have done.

**Comment by mulfranck** [comment]
Thanks, we all understand how to work together by now.

**Comment by Akashiutchiha** [comment]
Waoooh this issue has been fixed. Hope everyone here knows how to fetch
